In [1]:
import pandas as pd
import os
from pypapago import Translator
ts = Translator()

In [2]:
place_df = pd.read_csv('../../data/all_places_reviews.csv')
word_cluster = pd.read_csv('../../data/Go_adj_clustered.csv')
each_place_df = pd.read_csv('../../data/kakao_reviews_each_place.csv')

In [3]:
import os
folder_id = set(os.listdir("../../data/kakao_reviews"))
df_id = set(each_place_df['p_id'])

In [4]:
null_kakao_places = list(folder_id - df_id)

In [7]:
len(null_kakao_places)

23

In [22]:
null_kakao_places

['a107',
 'a86',
 'a39',
 'a510',
 'a90',
 'a310',
 'a412',
 'a914',
 'a912',
 'a93',
 'a81',
 'a710',
 'a108',
 'a713',
 'a610',
 'a1110',
 'a35',
 'a117',
 'a92',
 'a911',
 'a29',
 'a74',
 'a118']

In [6]:
len(folder_id)

1101

In [8]:
each_place_df

,p_id,review,review_en
0,f239,최고예요. 편안하게 있다 갔어요. 분위기 작살!!. 분위기죠아요 연남동에서 유일하게...,It's the best. It's comfortable. He's gone. Th...
1,b209,희수야효선왕돈까스 쌍문1줄번게,Heesuya Hyosun king pork cutlet Ssangmun No.1
2,e810,더홀 했는데... 좀 부실해요. 가지마세요 상자 자물쇠도 안채워놓는 세팅실수해놓아서...,It was a little duhol. It's a little weak. Don...
3,a211,신나는 분위기에서 한잔하며 볼링 즐길 수 있는 곳. 좋은 분위기 속에서 맛있는 칵테...,A place where you can drink and enjoy bowling ...
4,b44,걷기 길찾기 하면 배수로로 안내하니 괜히 헤매지말고 바로 노을공원입구로 가시오. 풍...,"If you find a way to walk, you will be guided ..."
...,...,...,...
1073,f2510,쾌적하고 다양한 보드겜도 많고 좋아요!! 재밌게 놀고 갔어요!!! 강남 룸카페는 여...,There are a lot of fun and diverse board games...
1074,b3312,도심속의 소 정원...숨겨진 산책길...The best place....,The cattle garden in the city center...Hidden ...
1075,c166,주말에도 깨끗하고 좋았어요 ! 치킨마요 맛있어요!. 평일에 가는걸 추천함 주말엔 ...,It was clean and nice on the weekend! Chicken...
1076,f414,강아지한테물려써요 우이이유ㅠㅠ. 개한테 관심도없고 만지지도 않앗는데 화장실 갓다왓다...,NaN
1077,b1213,"노인들, 그지들 많아서 더러움","Older people, dirty because they have a lot of..."

In [11]:
for place in null_kakao_places:
    df = pd.read_csv(f'../../data/kakao_reviews/{place}')
    all_review = ''
    all_en_review = ''
    p_id = df['p_id'][0]
    for i in range (0, len(df)):
        review = df['review'][i]
        try:
            review_en = ts.translate(review, source='ko', target='en', verbose=False)
        except:
            print(place, i)
            review_en = ''
        all_review = all_review+'. '+review;
        all_en_review = all_en_review+'. '+review_en
    each_place_df = each_place_df.append({'p_id':p_id, 'review':all_review, 'review_en': all_en_review}, ignore_index=True)

a1110 0

In [14]:
each_place_df.reset_index(inplace=True)

In [20]:
each_place_df.drop_duplicates(['p_id'],inplace=True)

In [23]:
del each_place_df['index']

In [25]:
each_place_df.to_csv('../../data/kakao_reviews_each_place.csv', index=False)

In [31]:
for i in os.listdir("../../data/kakao_places"):
    df = pd.read_csv(f'../../data/kakao_places/{i}')
    df.drop_duplicates(['p_name', 'address'], inplace=True)
    df.to_csv(f'../../data/kakao_places/{i}', index=False)

In [85]:
df = pd.read_csv(f'../../data/kakao_places/{"kakao_places_a.csv"}')
for i in os.listdir("../../data/kakao_places"):
    df = pd.concat([df, pd.read_csv(f'../../data/kakao_places/{i}')])

In [86]:
df.drop_duplicates(inplace=True)

In [88]:
df_a = df.drop_duplicates(['p_id'])

In [90]:
df

,open_day,link,p_rate,p_name,tags,open_time,category,p_id,address,price
0,연중무휴,https://place.map.kakao.com/17151176#comment,0/5,삼보락볼링장,"볼링장, 24시간영업, 즐거운 볼링장, 데이트코스, 야광볼링장.",볼링장,a,a10,서울 중랑구 중랑천로10길 76 (우)02124,NaN
1,매일 10:00 ~ 02:00\n더보기,https://place.map.kakao.com/10937046#comment,0/5,한아름볼링프라자,NaN,볼링장,a,a11,서울 광진구 능동로13길 39 지하1층 (우)05016,NaN
2,NaN,https://place.map.kakao.com/155156905#comment,0/5,역삼볼링시티,NaN,볼링장,a,a12,서울 강남구 언주로85길 13 (우)06222,NaN
3,월~목 11:00 ~ 05:00\n더보기,https://place.map.kakao.com/20747491#comment,0/5,태화볼링센타,NaN,볼링장,a,a13,"서울 마포구 와우산로 111 지하1, 2층 (우)04054",NaN
4,NaN,https://place.map.kakao.com/195724001#comment,0/5,오란다볼링센터,NaN,볼링장,a,a14,서울 서초구 방배로33길 29 한신트리플 지하1층 (우)06562,NaN
...,...,...,...,...,...,...,...,...,...,...
138,NaN,https://place.map.kakao.com/688980088#comment,0/5,놀숲,NaN,카페,c,c197,서울 종로구 성균관로 12 (우)03074,NaN
139,매일 11:00 ~ 24:00,https://place.map.kakao.com/1386161664#comment,0/5,책보는고릴라,만화카페,북카페,c,c198,서울 은평구 연서로27길 17 3층 (우)03333,NaN
140,NaN,https://place.map.kakao.com/1137467814#comment,0/5,모지트,NaN,북카페,c,c199,서울 강동구 양재대로128길 14 (우)05302,NaN
141,NaN,https://place.map.kakao.com/1869648412#comment,0/5,콤마커피,NaN,카페,c,c1910,서울 강남구 강남대로102길 13-8 (우)06123,NaN
142,NaN,https://place.map.kakao.com/18840626#comment,0/5,모지트 군자역점,NaN,북카페,c,c1911,서울 광진구 능동로 302 3층 (우)04985,NaN

In [89]:
df_a

,open_day,link,p_rate,p_name,tags,open_time,category,p_id,address,price
0,연중무휴,https://place.map.kakao.com/17151176#comment,0/5,삼보락볼링장,"볼링장, 24시간영업, 즐거운 볼링장, 데이트코스, 야광볼링장.",볼링장,a,a10,서울 중랑구 중랑천로10길 76 (우)02124,NaN
1,매일 10:00 ~ 02:00\n더보기,https://place.map.kakao.com/10937046#comment,0/5,한아름볼링프라자,NaN,볼링장,a,a11,서울 광진구 능동로13길 39 지하1층 (우)05016,NaN
2,NaN,https://place.map.kakao.com/155156905#comment,0/5,역삼볼링시티,NaN,볼링장,a,a12,서울 강남구 언주로85길 13 (우)06222,NaN
3,월~목 11:00 ~ 05:00\n더보기,https://place.map.kakao.com/20747491#comment,0/5,태화볼링센타,NaN,볼링장,a,a13,"서울 마포구 와우산로 111 지하1, 2층 (우)04054",NaN
4,NaN,https://place.map.kakao.com/195724001#comment,0/5,오란다볼링센터,NaN,볼링장,a,a14,서울 서초구 방배로33길 29 한신트리플 지하1층 (우)06562,NaN
...,...,...,...,...,...,...,...,...,...,...
138,NaN,https://place.map.kakao.com/688980088#comment,0/5,놀숲,NaN,카페,c,c197,서울 종로구 성균관로 12 (우)03074,NaN
139,매일 11:00 ~ 24:00,https://place.map.kakao.com/1386161664#comment,0/5,책보는고릴라,만화카페,북카페,c,c198,서울 은평구 연서로27길 17 3층 (우)03333,NaN
140,NaN,https://place.map.kakao.com/1137467814#comment,0/5,모지트,NaN,북카페,c,c199,서울 강동구 양재대로128길 14 (우)05302,NaN
141,NaN,https://place.map.kakao.com/1869648412#comment,0/5,콤마커피,NaN,카페,c,c1910,서울 강남구 강남대로102길 13-8 (우)06123,NaN
142,NaN,https://place.map.kakao.com/18840626#comment,0/5,모지트 군자역점,NaN,북카페,c,c1911,서울 광진구 능동로 302 3층 (우)04985,NaN

In [44]:
# df.to_csv('../../data/kakao_reviews_each_place.csv', index=False)

In [45]:
each_place_df = pd.read_csv('../../data/kakao_reviews_each_place.csv')

In [48]:
each_place_df

,p_id,review,review_en
0,f239,최고예요. 편안하게 있다 갔어요. 분위기 작살!!. 분위기죠아요 연남동에서 유일하게...,It's the best. It's comfortable. He's gone. Th...
1,b209,희수야효선왕돈까스 쌍문1줄번게,Heesuya Hyosun king pork cutlet Ssangmun No.1
2,e810,더홀 했는데... 좀 부실해요. 가지마세요 상자 자물쇠도 안채워놓는 세팅실수해놓아서...,It was a little duhol. It's a little weak. Don...
3,a211,신나는 분위기에서 한잔하며 볼링 즐길 수 있는 곳. 좋은 분위기 속에서 맛있는 칵테...,A place where you can drink and enjoy bowling ...
4,b44,걷기 길찾기 하면 배수로로 안내하니 괜히 헤매지말고 바로 노을공원입구로 가시오. 풍...,"If you find a way to walk, you will be guided ..."
...,...,...,...
1073,f2510,쾌적하고 다양한 보드겜도 많고 좋아요!! 재밌게 놀고 갔어요!!! 강남 룸카페는 여...,There are a lot of fun and diverse board games...
1074,b3312,도심속의 소 정원...숨겨진 산책길...The best place....,The cattle garden in the city center...Hidden ...
1075,c166,주말에도 깨끗하고 좋았어요 ! 치킨마요 맛있어요!. 평일에 가는걸 추천함 주말엔 ...,It was clean and nice on the weekend! Chicken...
1076,f414,강아지한테물려써요 우이이유ㅠㅠ. 개한테 관심도없고 만지지도 않앗는데 화장실 갓다왓다...,NaN
1077,b1213,"노인들, 그지들 많아서 더러움","Older people, dirty because they have a lot of..."

In [52]:
delete_id_ls = list(set(each_place_df['p_id'])-set(df['p_id']))

In [58]:
len(delete_id_ls)

201

In [55]:
for i in delete_id_ls:
    idx = each_place_df[each_place_df['p_id'] == i].index
    each_place_df.drop(idx, inplace=True)

In [59]:
each_place_df.to_csv('../../data/kakao_reviews_each_place.csv', index=False)

In [61]:
kk=pd.read_csv('../../data/kakao_places.csv')

In [65]:
kk_d = kk.drop_duplicates(['p_name', 'address'])

In [66]:
kk_d

,p_id,p_name,address,tags,open_time,open_day,category,price,p_rate,link
0,b10,서울숲,서울 성동구 성수동1가 678-1,아이들이 좋아하는 바닥분수가 있어 더욱 시원하고 즐거운 서울숲,도시근린공원,매일 00:00 ~ 24:00 (무료 입장)\n더보기,b,NaN,0/5,https://place.map.kakao.com/11331488#comment
1,b11,남산공원,서울 중구 남산공원길 125-54 (우)04628,NaN,도시근린공원,NaN,b,NaN,0/5,https://place.map.kakao.com/8246129#comment
2,b12,여의도한강공원,서울 영등포구 여의도동 85,"여의도한강공원은 정치, 금융, 언론의 중심지인 여의도에 자리하고 있으며, 지하철ㆍ버...",도시근린공원,매일 00:00 ~ 24:00\n더보기,b,NaN,0/5,https://place.map.kakao.com/10952963#comment
3,b13,NaN,서울 서초구 신반포로11길 40 (우)06500,한강르네상스 사업으로 조성된 반포한강공원에서 반포대교 교량 양쪽에 설치된 달빛무지개...,도시근린공원,NaN,b,NaN,0/5,https://place.map.kakao.com/8142957#comment
4,b14,선유도공원,서울 영등포구 선유로 343 (우)07200,NaN,공원,매일 06:00 ~ 24:00,b,NaN,0/5,https://place.map.kakao.com/17163566#comment
...,...,...,...,...,...,...,...,...,...,...
972,g315,락휴코인노래연습장 신촌명물거리점,서울 서대문구 명물길 23 401호 (우)03776,NaN,노래방,NaN,g,NaN,0/5,https://place.map.kakao.com/1766438558#comment
973,g317,케이팝코인노래방,서울 구로구 경인로59길 8 태영프라자 2층 215호 (우)08210,NaN,노래방,NaN,g,NaN,0/5,https://place.map.kakao.com/335223409#comment
974,g3114,카페코노피자,서울 마포구 양화로 45 (우)04036,NaN,카페,NaN,g,NaN,0/5,https://place.map.kakao.com/19883662#comment
975,g327,피그코인노래연습장,서울 송파구 송파대로 404 (우)05667,NaN,노래방,NaN,g,NaN,0/5,https://place.map.kakao.com/200358003#comment
976,g3213,코노코노코인노래연습장,서울 동작구 사당로 200 (우)07009,NaN,노래방,NaN,g,NaN,0/5,https://place.map.kakao.com/1314708464#comment

In [69]:
a= pd.read_csv('../../data/kakao_places/kakao_places_a.csv')

In [73]:
each_place_df

,p_id,review,review_en
0,f239,최고예요. 편안하게 있다 갔어요. 분위기 작살!!. 분위기죠아요 연남동에서 유일하게...,It's the best. It's comfortable. He's gone. Th...
1,b209,희수야효선왕돈까스 쌍문1줄번게,Heesuya Hyosun king pork cutlet Ssangmun No.1
2,e810,더홀 했는데... 좀 부실해요. 가지마세요 상자 자물쇠도 안채워놓는 세팅실수해놓아서...,It was a little duhol. It's a little weak. Don...
3,a211,신나는 분위기에서 한잔하며 볼링 즐길 수 있는 곳. 좋은 분위기 속에서 맛있는 칵테...,A place where you can drink and enjoy bowling ...
4,b44,걷기 길찾기 하면 배수로로 안내하니 괜히 헤매지말고 바로 노을공원입구로 가시오. 풍...,"If you find a way to walk, you will be guided ..."
...,...,...,...
1072,c192,구파발에서 가장 아늑하게 쉬면서 띵가띵가 할 수 있는 곳. 사람이 없어서 오히려 좋...,"The most cozy place in Gupabal, where you can ..."
1074,b3312,도심속의 소 정원...숨겨진 산책길...The best place....,The cattle garden in the city center...Hidden ...
1075,c166,주말에도 깨끗하고 좋았어요 ! 치킨마요 맛있어요!. 평일에 가는걸 추천함 주말엔 ...,It was clean and nice on the weekend! Chicken...
1076,f414,강아지한테물려써요 우이이유ㅠㅠ. 개한테 관심도없고 만지지도 않앗는데 화장실 갓다왓다...,NaN
1077,b1213,"노인들, 그지들 많아서 더러움","Older people, dirty because they have a lot of..."

In [79]:
len(set(each_place_df['p_id']))

877

In [75]:
set(each_place_df['p_id']) - set(new_places['p_id'])

{'d15',
 'e311',
 'e812',
 'f131',
 'f132',
 'f133',
 'f1411',
 'f1412',
 'f1414',
 'f161',
 'f1612',
 'f1613',
 'f171',
 'f1710',
 'f181',
 'f1812',
 'f183',
 'f184',
 'f185',
 'f1912',
 'f193',
 'f198',
 'f211',
 'f219',
 'f220',
 'f2213',
 'f2214',
 'f222',
 'f223',
 'f225',
 'f230',
 'f234',
 'f265',
 'f270',
 'f283'}

In [120]:
df = pd.read_csv(f'../../data/kakao_places/{"kakao_places_a.csv"}')
for i in os.listdir("../../data/kakao_places"):
    df = pd.concat([df, pd.read_csv(f'../../data/kakao_places/{i}')])

In [121]:
df.drop_duplicates(inplace=True)

In [122]:
df

,open_day,link,p_rate,p_name,tags,open_time,category,p_id,address,price
0,연중무휴,https://place.map.kakao.com/17151176#comment,0/5,삼보락볼링장,"볼링장, 24시간영업, 즐거운 볼링장, 데이트코스, 야광볼링장.",볼링장,a,a10,서울 중랑구 중랑천로10길 76 (우)02124,NaN
1,매일 10:00 ~ 02:00\n더보기,https://place.map.kakao.com/10937046#comment,0/5,한아름볼링프라자,NaN,볼링장,a,a11,서울 광진구 능동로13길 39 지하1층 (우)05016,NaN
2,NaN,https://place.map.kakao.com/155156905#comment,0/5,역삼볼링시티,NaN,볼링장,a,a12,서울 강남구 언주로85길 13 (우)06222,NaN
3,월~목 11:00 ~ 05:00\n더보기,https://place.map.kakao.com/20747491#comment,0/5,태화볼링센타,NaN,볼링장,a,a13,"서울 마포구 와우산로 111 지하1, 2층 (우)04054",NaN
4,NaN,https://place.map.kakao.com/195724001#comment,0/5,오란다볼링센터,NaN,볼링장,a,a14,서울 서초구 방배로33길 29 한신트리플 지하1층 (우)06562,NaN
...,...,...,...,...,...,...,...,...,...,...
137,NaN,https://place.map.kakao.com/24840806#comment,0/5,놀이터만화,NaN,만화방,c,c912,서울 관악구 남부순환로 1491 (우)08761,NaN
138,NaN,https://place.map.kakao.com/918962838#comment,0/5,방콕만화카페,NaN,만화방,c,c92,서울 관악구 신림로 107 2층 (우)08813,NaN
139,매일 11:00 ~ 23:00,https://place.map.kakao.com/26777399#comment,0/5,만화카페딩굴,NaN,만화방,c,c93,서울 성북구 고려대로24길 44 (우)02855,NaN
140,NaN,https://place.map.kakao.com/26554486#comment,0/5,땡땡이치는만화카페,NaN,만화방,c,c97,서울 강서구 화곡로 130 동원빌딩 3층 (우)07718,NaN
141,NaN,https://place.map.kakao.com/26325912#comment,0/5,만화카페사랑애,도서대여 및 만화카페,만화방,c,c99,서울 광진구 용마산로 53 3층 (우)04923,NaN

In [123]:
df.groupby('p_id').filter(lambda x : len(x)>1)

Empty DataFrame
Columns: [open_day, link, p_rate, p_name, tags, open_time, category, p_id, address, price]
Index: []

In [124]:
df.drop_duplicates(['p_id'], inplace=True)

In [125]:
df

,open_day,link,p_rate,p_name,tags,open_time,category,p_id,address,price
0,연중무휴,https://place.map.kakao.com/17151176#comment,0/5,삼보락볼링장,"볼링장, 24시간영업, 즐거운 볼링장, 데이트코스, 야광볼링장.",볼링장,a,a10,서울 중랑구 중랑천로10길 76 (우)02124,NaN
1,매일 10:00 ~ 02:00\n더보기,https://place.map.kakao.com/10937046#comment,0/5,한아름볼링프라자,NaN,볼링장,a,a11,서울 광진구 능동로13길 39 지하1층 (우)05016,NaN
2,NaN,https://place.map.kakao.com/155156905#comment,0/5,역삼볼링시티,NaN,볼링장,a,a12,서울 강남구 언주로85길 13 (우)06222,NaN
3,월~목 11:00 ~ 05:00\n더보기,https://place.map.kakao.com/20747491#comment,0/5,태화볼링센타,NaN,볼링장,a,a13,"서울 마포구 와우산로 111 지하1, 2층 (우)04054",NaN
4,NaN,https://place.map.kakao.com/195724001#comment,0/5,오란다볼링센터,NaN,볼링장,a,a14,서울 서초구 방배로33길 29 한신트리플 지하1층 (우)06562,NaN
...,...,...,...,...,...,...,...,...,...,...
137,NaN,https://place.map.kakao.com/24840806#comment,0/5,놀이터만화,NaN,만화방,c,c912,서울 관악구 남부순환로 1491 (우)08761,NaN
138,NaN,https://place.map.kakao.com/918962838#comment,0/5,방콕만화카페,NaN,만화방,c,c92,서울 관악구 신림로 107 2층 (우)08813,NaN
139,매일 11:00 ~ 23:00,https://place.map.kakao.com/26777399#comment,0/5,만화카페딩굴,NaN,만화방,c,c93,서울 성북구 고려대로24길 44 (우)02855,NaN
140,NaN,https://place.map.kakao.com/26554486#comment,0/5,땡땡이치는만화카페,NaN,만화방,c,c97,서울 강서구 화곡로 130 동원빌딩 3층 (우)07718,NaN
141,NaN,https://place.map.kakao.com/26325912#comment,0/5,만화카페사랑애,도서대여 및 만화카페,만화방,c,c99,서울 광진구 용마산로 53 3층 (우)04923,NaN

In [126]:
df.to_csv('../../data/kakao_places.csv', index=False)

In [148]:
each_place_df = pd.read_csv('../../data/kakao_reviews_each_place.csv')

In [149]:
each_place_df

,p_id,review,review_en
0,f239,최고예요. 편안하게 있다 갔어요. 분위기 작살!!. 분위기죠아요 연남동에서 유일하게...,It's the best. It's comfortable. He's gone. Th...
1,b209,희수야효선왕돈까스 쌍문1줄번게,Heesuya Hyosun king pork cutlet Ssangmun No.1
2,e810,더홀 했는데... 좀 부실해요. 가지마세요 상자 자물쇠도 안채워놓는 세팅실수해놓아서...,It was a little duhol. It's a little weak. Don...
3,a211,신나는 분위기에서 한잔하며 볼링 즐길 수 있는 곳. 좋은 분위기 속에서 맛있는 칵테...,A place where you can drink and enjoy bowling ...
4,b44,걷기 길찾기 하면 배수로로 안내하니 괜히 헤매지말고 바로 노을공원입구로 가시오. 풍...,"If you find a way to walk, you will be guided ..."
...,...,...,...
891,a29,". 공상태, 바닥상태 엉망. 일요일 여자 카운터 알바 노친절. 굉장히 깔끔한 분위...",". Air space, floor conditions, mess. Sunday W..."
892,a710,. 역시 난 볼링에 천재*^^*. 마인드가 썩었네 다른볼링장 가라는게 이 볼링장 ...,. Of course I'm a bowling genius at bowling.. ...
893,a35,. 직원개판. 알바생 ㅈㄴ 싸가지없음. 알바천국. 알바랑 친하면 볼링화 안신고 운동...,. Employee opening. You're a part-timer. You'r...
894,a310,. 클럽음악이 계속 나와 다소 시끄럽습니다. 청력이 약하신 분은 주의하세요.. 좋아...,". Club music keeps coming out, so it's a bit n..."
895,a412,. 앵간하면 가지마셈 사장성격이상함,". Don't go when you're angry, boss. Unusual pe..."

In [146]:
del each_place_df['Unnamed: 0']

In [140]:
null_review = set(df['p_id']) - set(each_place_df['p_id'])

In [139]:
for place in null_review:
    df = pd.read_csv(f'../../data/kakao_reviews/{place}')
    all_review = ''
    all_en_review = ''
    p_id = df['p_id'][0]
    for i in range (0, len(df)):
        review = df['review'][i]
        try:
            review_en = ts.translate(review, source='ko', target='en', verbose=False)
        except:
            print(place, i)
            review_en = ''
        all_review = all_review+'. '+review;
        all_en_review = all_en_review+'. '+review_en
    each_place_df = each_place_df.append({'p_id':p_id, 'review':all_review, 'review_en': all_en_review}, ignore_index=True)

In [142]:
each_place_df.groupby('p_id').filter(lambda x : len(x)>1)

Empty DataFrame
Columns: [p_id, review, review_en]
Index: []

In [147]:
each_place_df.to_csv('../../data/kakao_reviews_each_place.csv', index=False)